--- 
abstract: HTTP::Response That Writes To Disk
author: Copyright (c) 2007 Daisuke Maki <daisuke@endeworks.jp>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: HTTP-Response-OnDisk
no_index: 
  directory: 
    - inc
    - t
recommends: 
  Encode: 0
  IO::Uncompress::Bunzip2: 0
  IO::Uncompress::Gunzip: 0
  MIME::Base64: 0
  MIME::QuotedPrint: 0
requires: 
  Class::Accessor::Fast: 0
  Class::Data::Inheritable: 0
  Class::Inspector: 0
  Fcntl: 0
  File::Spec: 0
  File::Temp: 0
  HTTP::Headers: 0
  HTTP::Status: 0
  Path::Class::Dir: 0
version: 0.02
